server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # INI OBATNYA: Jika file tidak ketemu, lempar ke index.html
        try_files $uri $uri/ /index.html; 
    }
}